# Generated by Django 6.1.2 on 2026-10-07 16:53

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short description shown in article listings",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("richtext", 0), ("image", 1), ("quote", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Formatted text block",
                                    "label": "Rich Text",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Upload or choose an image from the media library",
                                    "label": "Image",
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Quote text"},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Author", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 2), ("author", 3)]],
                                {"label": "Pull Quote"},
                            ),
                        },
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="content.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Page",
                "verbose_name_plural": "Article Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
